// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2025-2026 ecoPrimals Collective

//
// Core types and structures used by the performance dashboard system.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::Duration;
use std::time::SystemTime;

/// **DASHBOARD TIME RANGE**
///
/// Time range specification for dashboard data queries.
#[derive(Debug, Clone, Serialize, Deserialize)]
/// Dashboardtimerange
pub struct DashboardTimeRange {
    /// Start time of the range
    pub start: SystemTime,
    /// End time of the range
    pub end: SystemTime,
    /// Data granularity for aggregation
    pub granularity: Duration,
}
impl DashboardTimeRange {
    /// Create a new time range
    #[must_use]
    pub const fn new(start: SystemTime, end: SystemTime, granularity: Duration) -> Self {
        Self {
            start,
            end,
            granularity,
        }
    }

    /// Create a time range for the last N hours
    #[must_use]
    pub fn last_hours(hours: u64) -> Self {
        let end = SystemTime::now();
        let start = end - Duration::from_secs(hours * 3600);
        Self {
            start,
            end,
            granularity: Duration::from_secs(300), // 5 minutes
        }
    }

    /// Create a time range for the last N days
    #[must_use]
    pub fn last_days(days: u64) -> Self {
        let end = SystemTime::now();
        let start = end - Duration::from_secs(days * 24 * 3600);
        Self {
            start,
            end,
            granularity: Duration::from_secs(3600), // 1 hour
        }
    }

    /// Get duration of this time range
    #[must_use]
    pub fn duration(&self) -> Duration {
        self.end
            .duration_since(self.start)
            .unwrap_or(Duration::ZERO)
    }

    /// Check if this time range is valid
    #[must_use]
    pub fn is_valid(&self) -> bool {
        self.start < self.end && !self.granularity.is_zero()
    }

    /// Get the number of data points in this range
    #[must_use]
    pub fn data_points(&self) -> usize {
        if !self.is_valid() {
            return 0;
        }
        let duration = self.duration();
        (duration.as_secs() / self.granularity.as_secs()).max(1) as usize
    }

    /// Split time range into intervals based on granularity
    #[must_use]
    pub fn intervals(&self) -> Vec<(SystemTime, SystemTime)> {
        let mut intervals = Vec::new();
        let mut current = self.start;

        while current < self.end {
            let next = current + self.granularity;
            let interval_end = if next > self.end { self.end } else { next };
            intervals.push((current, interval_end));
            current = next;
        }

        intervals
    }
}

/// Dashboard state for real-time updates
#[derive(Debug)]
/// Dashboardstate
pub struct DashboardState {
    /// Current active connections
    pub active_connections: u32,
    /// Last update timestamp
    pub last_update: SystemTime,
    /// Cached metrics for quick access
    pub cached_metrics: HashMap<String, serde_json::Value>,
    /// Performance alerts
    pub active_alerts: Vec<PerformanceAlert>,
}
impl DashboardState {
    /// Create a new dashboard state instance
    #[must_use]
    pub fn new() -> Self {
        Self {
            active_connections: 0,
            last_update: SystemTime::now(),
            cached_metrics: HashMap::new(),
            active_alerts: Vec::new(),
        }
    }

    /// Update metrics with new key-value pair
    pub fn update_metrics(&mut self, key: String, value: serde_json::Value) {
        self.cached_metrics.insert(key, value);
        self.last_update = SystemTime::now();
    }

    /// Add a new performance alert to the dashboard
    pub fn add_alert(&mut self, alert: PerformanceAlert) {
        self.active_alerts.push(alert);
    }

    /// Remove resolved alerts from the dashboard
    pub fn clear_resolved_alerts(&mut self) {
        self.active_alerts.retain(|alert| !alert.resolved);
    }
}

impl Default for DashboardState {
    /// Returns the default instance
    fn default() -> Self {
        Self::new()
    }
}

/// **PERFORMANCE ALERT**
///
/// Alert generated by performance monitoring system.
#[derive(Debug, Clone, Serialize, Deserialize)]
/// Performancealert
pub struct PerformanceAlert {
    /// Unique alert identifier
    pub id: String,
    /// Severity level of the alert
    pub severity: AlertSeverity,
    /// Alert title for display
    pub title: String,
    /// Detailed alert message
    pub message: String,
    /// Timestamp when alert was generated
    pub timestamp: SystemTime,
    /// Whether the alert has been resolved
    pub resolved: bool,
    /// Name of the metric that triggered the alert
    pub metric_name: String,
    /// Current value of the metric
    pub currentvalue: f64,
    /// Threshold value that was exceeded
    pub threshold: f64,
}
/// Alert severity levels
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
/// Alertseverity
pub enum AlertSeverity {
    /// Informational message, no action required
    Info,
    /// Warning condition that should be monitored
    Warning,
    /// Critical condition requiring immediate attention
    Critical,
    /// Emergency condition requiring urgent intervention
    Emergency,
}
/// **DASHBOARD EVENT**
///
/// Event that occurred in the dashboard system for real-time updates.
#[derive(Debug, Clone, Serialize, Deserialize)]
/// Dashboardevent
pub struct DashboardEvent {
    /// Type of event that occurred
    pub event_type: String,
    /// Event data payload
    pub data: serde_json::Value,
    /// Timestamp when event occurred
    pub timestamp: SystemTime,
}
/// Dashboard configuration
#[derive(Debug, Clone)]
/// DEPRECATED: This config has been consolidated into `canonical_primary`
///
/// **Migration Path**:
/// ```rust,ignore
/// // OLD (deprecated):
/// use crate::network::config::DashboardConfig;
///
/// // NEW (canonical):
/// use nestgate_core::config::canonical_primary::domains::network::CanonicalNetworkConfig;
/// // Or use type alias for compatibility:
/// use crate::network::config::DashboardConfig; // Now aliases to CanonicalNetworkConfig
/// ```
///
/// **Timeline**: This type alias will be maintained until v0.12.0 (May 2026)
/// Configuration for Dashboard
pub struct DashboardConfig {
    /// Enable real-time updates
    pub enable_real_time: bool,
    /// Update interval for real-time data
    pub update_interval: Duration,
    /// Maximum history to keep in memory
    pub max_history_points: usize,
    /// Enable predictive analytics
    pub enable_predictions: bool,
    /// Alert thresholds
    pub alert_thresholds: HashMap<String, f64>,
}
impl Default for DashboardConfig {
    /// Returns the default instance
    fn default() -> Self {
        let mut alert_thresholds = HashMap::new();
        alert_thresholds.insert("cpu_usage".to_string(), 80.0);
        alert_thresholds.insert("memory_usage".to_string(), 85.0);
        alert_thresholds.insert("disk_usage".to_string(), 90.0);
        alert_thresholds.insert("latency_ms".to_string(), 1000.0);
        alert_thresholds.insert("error_rate".to_string(), 5.0);

        Self {
            enable_real_time: true,
            update_interval: Duration::from_secs(1),
            max_history_points: 1000,
            enable_predictions: true,
            alert_thresholds,
        }
    }
}

// ==================== CANONICAL TYPE ALIAS ====================
// This type now aliases to the canonical network configuration
// Original struct definition kept above for reference and backward compatibility

/// Type alias to canonical network configuration
///
/// This provides backward compatibility while migrating to unified configuration.
/// The original struct is marked as deprecated but still functional.
/// Type alias for Dashboardconfigcanonical
pub type DashboardConfigCanonical =
    nestgate_core::config::canonical_primary::domains::network::CanonicalNetworkConfig;

// Note: Keep using DashboardConfig (the deprecated struct) for now.
// We'll gradually migrate to CanonicalNetworkConfig directly in a later phase.
// This alias is here for reference and future migration.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dashboard_time_range_new() {
        let start = SystemTime::now();
        let end = start + Duration::from_secs(3600);
        let granularity = Duration::from_secs(60);

        let range = DashboardTimeRange::new(start, end, granularity);

        assert_eq!(range.start, start);
        assert_eq!(range.end, end);
        assert_eq!(range.granularity, granularity);
    }

    #[test]
    fn test_dashboard_time_range_last_hours() {
        let range = DashboardTimeRange::last_hours(24);

        assert!(range.is_valid());
        assert_eq!(range.granularity, Duration::from_secs(300)); // 5 minutes

        // Verify duration is approximately 24 hours (allow some tolerance)
        let duration = range.duration().as_secs();
        let expected = 24 * 3600;
        assert!(duration.abs_diff(expected) < 5);
    }

    #[test]
    fn test_dashboard_time_range_last_days() {
        let range = DashboardTimeRange::last_days(7);

        assert!(range.is_valid());
        assert_eq!(range.granularity, Duration::from_secs(3600)); // 1 hour

        // Verify duration is approximately 7 days (allow some tolerance)
        let duration = range.duration().as_secs();
        let expected = 7 * 24 * 3600;
        assert!(duration.abs_diff(expected) < 5);
    }

    #[test]
    fn test_dashboard_time_range_duration() {
        let start = SystemTime::UNIX_EPOCH;
        let end = start + Duration::from_secs(3600);
        let range = DashboardTimeRange::new(start, end, Duration::from_secs(60));

        assert_eq!(range.duration(), Duration::from_secs(3600));
    }

    #[test]
    fn test_dashboard_time_range_is_valid() {
        let start = SystemTime::now();
        let end = start + Duration::from_secs(3600);

        // Valid range
        let range = DashboardTimeRange::new(start, end, Duration::from_secs(60));
        assert!(range.is_valid());

        // Invalid range (end before start)
        let invalid_range = DashboardTimeRange::new(end, start, Duration::from_secs(60));
        assert!(!invalid_range.is_valid());

        // Invalid range (zero granularity)
        let zero_gran = DashboardTimeRange::new(start, end, Duration::ZERO);
        assert!(!zero_gran.is_valid());
    }

    #[test]
    fn test_dashboard_time_range_data_points() {
        let start = SystemTime::UNIX_EPOCH;
        let end = start + Duration::from_secs(3600);
        let range = DashboardTimeRange::new(start, end, Duration::from_secs(60));

        assert_eq!(range.data_points(), 60);
    }

    #[test]
    fn test_dashboard_time_range_intervals() {
        let start = SystemTime::UNIX_EPOCH;
        let end = start + Duration::from_secs(300);
        let range = DashboardTimeRange::new(start, end, Duration::from_secs(100));

        let intervals = range.intervals();
        assert_eq!(intervals.len(), 3);

        // First interval
        assert_eq!(intervals[0].0, start);
        assert_eq!(intervals[0].1, start + Duration::from_secs(100));

        // Last interval should end exactly at range end
        assert_eq!(intervals[2].1, end);
    }

    #[test]
    fn test_dashboard_state_new() {
        let state = DashboardState::new();

        assert_eq!(state.active_connections, 0);
        assert!(state.cached_metrics.is_empty());
        assert!(state.active_alerts.is_empty());
    }

    #[test]
    fn test_dashboard_state_default() {
        let state = DashboardState::default();

        assert_eq!(state.active_connections, 0);
        assert!(state.cached_metrics.is_empty());
    }

    #[test]
    fn test_dashboard_state_update_metrics() {
        let mut state = DashboardState::new();

        state.update_metrics("cpu_usage".to_string(), serde_json::json!(45.5));
        state.update_metrics("memory_usage".to_string(), serde_json::json!(67.8));

        assert_eq!(state.cached_metrics.len(), 2);
        assert_eq!(
            state.cached_metrics.get("cpu_usage"),
            Some(&serde_json::json!(45.5))
        );
    }

    #[test]
    fn test_dashboard_state_add_alert() {
        let mut state = DashboardState::new();

        let alert = PerformanceAlert {
            id: "alert_001".to_string(),
            severity: AlertSeverity::Warning,
            title: "High CPU".to_string(),
            message: "CPU usage exceeded threshold".to_string(),
            timestamp: SystemTime::now(),
            resolved: false,
            metric_name: "cpu_usage".to_string(),
            currentvalue: 85.0,
            threshold: 80.0,
        };

        state.add_alert(alert);
        assert_eq!(state.active_alerts.len(), 1);
    }

    #[test]
    fn test_dashboard_state_clear_resolved_alerts() {
        let mut state = DashboardState::new();

        // Add resolved alert
        state.add_alert(PerformanceAlert {
            id: "alert_001".to_string(),
            severity: AlertSeverity::Warning,
            title: "Test".to_string(),
            message: "Test".to_string(),
            timestamp: SystemTime::now(),
            resolved: true,
            metric_name: "test".to_string(),
            currentvalue: 50.0,
            threshold: 40.0,
        });

        // Add unresolved alert
        state.add_alert(PerformanceAlert {
            id: "alert_002".to_string(),
            severity: AlertSeverity::Critical,
            title: "Test2".to_string(),
            message: "Test2".to_string(),
            timestamp: SystemTime::now(),
            resolved: false,
            metric_name: "test2".to_string(),
            currentvalue: 90.0,
            threshold: 80.0,
        });

        state.clear_resolved_alerts();
        assert_eq!(state.active_alerts.len(), 1);
        assert_eq!(state.active_alerts[0].id, "alert_002");
    }

    #[test]
    fn test_performance_alert_serialization() {
        let alert = PerformanceAlert {
            id: "alert_123".to_string(),
            severity: AlertSeverity::Critical,
            title: "High Memory Usage".to_string(),
            message: "Memory usage exceeded threshold".to_string(),
            timestamp: SystemTime::now(),
            resolved: false,
            metric_name: "memory_usage".to_string(),
            currentvalue: 92.5,
            threshold: 85.0,
        };

        let json = serde_json::to_string(&alert);
        assert!(json.is_ok());
    }

    #[test]
    fn test_alert_severity_ordering() {
        assert!(AlertSeverity::Info < AlertSeverity::Warning);
        assert!(AlertSeverity::Warning < AlertSeverity::Critical);
        assert!(AlertSeverity::Critical < AlertSeverity::Emergency);
    }

    #[test]
    fn test_dashboard_event_serialization() {
        let event = DashboardEvent {
            event_type: "metric_updated".to_string(),
            data: serde_json::json!({"cpu": 45.2}),
            timestamp: SystemTime::now(),
        };

        let json = serde_json::to_string(&event);
        assert!(json.is_ok());
    }

    #[test]
    #[expect(deprecated)]
    fn test_dashboard_config_default() {
        let config = DashboardConfig::default();

        assert!(config.enable_real_time);
        assert_eq!(config.update_interval, Duration::from_secs(1));
        assert_eq!(config.max_history_points, 1000);
        assert!(config.enable_predictions);

        // Check default alert thresholds
        assert_eq!(config.alert_thresholds.get("cpu_usage"), Some(&80.0));
        assert_eq!(config.alert_thresholds.get("memory_usage"), Some(&85.0));
        assert_eq!(config.alert_thresholds.get("disk_usage"), Some(&90.0));
    }
}
