#!/bin/bash
# Hardcoding Elimination Script for NestGate
# This script systematically migrates hardcoded values to configuration

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "🔧 NestGate Hardcoding Elimination Script"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Phase 1: Audit Current Hardcoding
echo -e "${BLUE}Phase 1: Auditing Current Hardcoding${NC}"
echo "--------------------------------------"

echo "📊 Counting hardcoded ports..."
PORT_COUNT=$(grep -r "8080\|3000\|5432\|6379\|9090\|27017\|5000" code/crates --include="*.rs" | grep -v "test\|spec\|example" | wc -l || echo "0")
echo "   Found: $PORT_COUNT instances"

echo "📊 Counting hardcoded IPs..."
IP_COUNT=$(grep -r "127\.0\.0\.1\|localhost" code/crates --include="*.rs" | grep -v "test\|spec\|example" | wc -l || echo "0")
echo "   Found: $IP_COUNT instances"

echo "📊 Counting DEFAULT_ constants..."
DEFAULT_COUNT=$(grep -r "const DEFAULT_" code/crates --include="*.rs" | wc -l || echo "0")
echo "   Found: $DEFAULT_COUNT instances"

echo ""

# Phase 2: Create Configuration Template
echo -e "${BLUE}Phase 2: Creating Configuration Template${NC}"
echo "----------------------------------------"

CONFIG_FILE="config/canonical-master-generated.toml"
echo "📝 Generating configuration template: $CONFIG_FILE"

cat > "$CONFIG_FILE" << 'EOF'
# NestGate Canonical Master Configuration
# Generated by hardcoding elimination script
# Date: $(date +"%Y-%m-%d %H:%M:%S")

[api]
# API server configuration
host = "0.0.0.0"
port = 8080
timeout_seconds = 30
max_connections = 1000

[development]
# Development server configuration
port = 3000
hot_reload = true
debug_mode = false

[database]
# Database connection configuration
[database.postgresql]
host = "localhost"
port = 5432
database = "nestgate"
max_connections = 10

[database.redis]
host = "localhost"
port = 6379
database = 0
max_connections = 10

[database.mongodb]
host = "localhost"
port = 27017
database = "nestgate"
max_connections = 10

[monitoring]
# Monitoring and metrics configuration
prometheus_port = 9090
grafana_port = 3001
enable_metrics = true

[primal_discovery]
# Primal discovery service configuration
port = 5000
timeout_seconds = 5
retry_attempts = 3

[network]
# Network configuration defaults
connect_timeout_seconds = 10
read_timeout_seconds = 30
write_timeout_seconds = 30

[zfs]
# ZFS-specific configuration
pool_check_interval_seconds = 60
snapshot_retention_days = 30

[security]
# Security configuration
tls_enabled = false
cert_path = "/etc/nestgate/certs"
key_path = "/etc/nestgate/keys"

[logging]
# Logging configuration
level = "info"
format = "json"
output = "stdout"

EOF

echo -e "${GREEN}✅ Configuration template created${NC}"
echo ""

# Phase 3: Generate Migration Report
echo -e "${BLUE}Phase 3: Generating Migration Report${NC}"
echo "------------------------------------"

REPORT_FILE="HARDCODING_MIGRATION_PROGRESS.md"
echo "📊 Creating migration report: $REPORT_FILE"

cat > "$REPORT_FILE" << EOF
# Hardcoding Migration Progress Report

**Generated**: $(date +"%Y-%m-%d %H:%M:%S")  
**Status**: In Progress

## Summary

| Category | Count | Status |
|----------|-------|--------|
| Hardcoded Ports | $PORT_COUNT | 🔄 Pending |
| Hardcoded IPs | $IP_COUNT | 🔄 Pending |
| DEFAULT_ Constants | $DEFAULT_COUNT | 🔄 Pending |

## Migration Strategy

### Phase 1: Port Migration (Estimated: 3-4 days)
Replace hardcoded ports with configuration values:

\`\`\`rust
// BEFORE:
let addr = "0.0.0.0:8080".parse().unwrap();

// AFTER:
let config = Config::load()?;
let addr = format!("{}:{}", config.api.host, config.api.port)
    .parse()
    .map_err(|e| NestGateError::Configuration(e))?;
\`\`\`

### Phase 2: IP/Hostname Migration (Estimated: 2-3 days)
Replace hardcoded addresses with configuration:

\`\`\`rust
// BEFORE:
let redis_url = "redis://127.0.0.1:6379";

// AFTER:
let config = Config::load()?;
let redis_url = format!(
    "redis://{}:{}", 
    config.database.redis.host, 
    config.database.redis.port
);
\`\`\`

### Phase 3: Constants Migration (Estimated: 5-6 days)
Move DEFAULT_ constants to configuration:

\`\`\`rust
// BEFORE:
const DEFAULT_TIMEOUT: u64 = 30;

// AFTER:
// In config struct:
pub struct NetworkConfig {
    pub connect_timeout_seconds: u64,
}

// Usage:
let timeout = Duration::from_secs(config.network.connect_timeout_seconds);
\`\`\`

## Priority Files to Migrate

### High Priority (API Handlers)
- [ ] \`code/crates/nestgate-api/src/main.rs\` - API server binding
- [ ] \`code/crates/nestgate-api/src/bin/nestgate-api-server.rs\` - Server initialization

### Medium Priority (Core Services)
- [ ] \`code/crates/nestgate-core/src/network/client.rs\` - Network client
- [ ] \`code/crates/nestgate-core/src/config/network_defaults.rs\` - Network defaults
- [ ] \`code/crates/nestgate-core/src/constants/port_defaults.rs\` - Port constants

### Low Priority (Tests & Examples)
- [ ] Test files (acceptable to keep hardcoded for testing)
- [ ] Example files (acceptable to show specific values)

## Timeline

- **Week 1**: Port migration (days 1-4)
- **Week 2**: IP/hostname migration (days 5-7) + Constants migration start (days 8-10)
- **Week 3**: Constants migration completion (days 11-14)
- **Total**: 10-14 days

## Testing Strategy

1. **Unit Tests**: Verify config loading
2. **Integration Tests**: Test with different config values
3. **E2E Tests**: Deploy with various configurations
4. **Backward Compatibility**: Support environment variables as fallback

## Next Steps

1. Run this script to generate base configuration
2. Review generated \`$CONFIG_FILE\`
3. Start with high-priority files
4. Add tests for each migrated component
5. Update documentation

EOF

echo -e "${GREEN}✅ Migration report created${NC}"
echo ""

# Phase 4: Create Helper Functions
echo -e "${BLUE}Phase 4: Creating Helper Functions${NC}"
echo "----------------------------------"

HELPER_FILE="code/crates/nestgate-core/src/config/migration_helpers.rs"
echo "📝 Creating migration helper functions: $HELPER_FILE"

mkdir -p "$(dirname "$HELPER_FILE")"

cat > "$HELPER_FILE" << 'RUST_EOF'
//! Configuration Migration Helpers
//!
//! Helper functions to safely migrate from hardcoded values to configuration.

use crate::error::{NestGateError, Result};
use std::env;

/// Get configuration value with environment variable fallback
///
/// Tries environment variable first, then falls back to config value,
/// then to default value if provided.
pub fn get_with_fallback<T>(
    env_var: &str,
    config_value: Option<T>,
    default: T,
) -> T
where
    T: std::str::FromStr + Clone,
{
    // Try environment variable first
    if let Ok(val) = env::var(env_var) {
        if let Ok(parsed) = val.parse::<T>() {
            return parsed;
        }
    }

    // Fall back to config value
    if let Some(val) = config_value {
        return val;
    }

    // Use default
    default
}

/// Get port with multiple fallback options
///
/// Priority: ENV var > Config > Default
pub fn get_port(env_var: &str, config_port: Option<u16>, default: u16) -> u16 {
    get_with_fallback(env_var, config_port, default)
}

/// Get host with multiple fallback options
///
/// Priority: ENV var > Config > Default
pub fn get_host(env_var: &str, config_host: Option<String>, default: &str) -> String {
    if let Ok(host) = env::var(env_var) {
        return host;
    }
    config_host.unwrap_or_else(|| default.to_string())
}

/// Build address from host and port
pub fn build_address(host: &str, port: u16) -> Result<String> {
    if host.is_empty() {
        return Err(NestGateError::Configuration(
            "Host cannot be empty".to_string(),
        ));
    }
    Ok(format!("{}:{}", host, port))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_port_with_env() {
        env::set_var("TEST_PORT", "9999");
        let port = get_port("TEST_PORT", Some(8080), 3000);
        assert_eq!(port, 9999);
        env::remove_var("TEST_PORT");
    }

    #[test]
    fn test_get_port_with_config() {
        let port = get_port("NONEXISTENT_PORT", Some(8080), 3000);
        assert_eq!(port, 8080);
    }

    #[test]
    fn test_get_port_with_default() {
        let port = get_port("NONEXISTENT_PORT", None, 3000);
        assert_eq!(port, 3000);
    }

    #[test]
    fn test_build_address() {
        let addr = build_address("localhost", 8080).unwrap();
        assert_eq!(addr, "localhost:8080");
    }

    #[test]
    fn test_build_address_empty_host() {
        let result = build_address("", 8080);
        assert!(result.is_err());
    }
}
RUST_EOF

echo -e "${GREEN}✅ Helper functions created${NC}"
echo ""

# Summary
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}✅ Hardcoding Elimination Setup Complete${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "📋 Generated Files:"
echo "   - $CONFIG_FILE (configuration template)"
echo "   - $REPORT_FILE (migration progress report)"
echo "   - $HELPER_FILE (migration helper functions)"
echo ""
echo "📖 Next Steps:"
echo "   1. Review generated configuration template"
echo "   2. Read migration progress report"
echo "   3. Start migrating high-priority files"
echo "   4. Use helper functions for safe migration"
echo ""
echo -e "${YELLOW}⚠️  Remember: Test each migration thoroughly!${NC}"
echo ""

