use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstallerConfig {
    pub install_path: PathBuf,
    pub service_mode: bool,
    pub enable_zfs: bool,
    pub api_port: u16,
    pub orchestration_url: Option<String>,
    pub ai_enabled: bool,
    pub create_desktop_shortcut: bool,
    pub add_to_path: bool,
}

impl Default for InstallerConfig {
    fn default() -> Self {
        Self {
            install_path: default_install_path(),
            service_mode: true,
            enable_zfs: true,
            api_port: std::env::var("NESTGATE_API_PORT")
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(8080),
            orchestration_url: None,
            ai_enabled: false,
            create_desktop_shortcut: true,
            add_to_path: true,
        }
    }
}

impl InstallerConfig {
    pub fn validate(&self) -> Result<()> {
        if self.api_port < 1024 && !is_privileged() {
            anyhow::bail!("Port {} requires administrator privileges", self.api_port);
        }

        if !self.install_path.parent().is_some_and(|p| p.exists()) {
            anyhow::bail!(
                "Installation directory parent does not exist: {:?}",
                self.install_path.parent()
            );
        }

        Ok(())
    }

    pub fn to_nestgate_config(&self) -> String {
        let host = std::env::var("NESTGATE_HOST").unwrap_or_else(|_| "127.0.0.1".to_string());
        let default_orchestration_port =
            std::env::var("NESTGATE_UI_PORT").unwrap_or_else(|_| "3000".to_string());

        format!(
            r#"# NestGate Configuration
# Generated by nestgate-installer

[api]
host = "{}"
port = {}

[zfs]
enabled = {}

[ai]
enabled = {}

[orchestration]
{}

[logging]
level = "info"
"#,
            host,
            self.api_port,
            self.enable_zfs,
            self.ai_enabled,
            if let Some(url) = &self.orchestration_url {
                format!("url = \"{}\"", url)
            } else {
                format!(
                    "# url = \"http://localhost:{}\"",
                    default_orchestration_port
                )
            }
        )
    }
}

fn default_install_path() -> PathBuf {
    #[cfg(windows)]
    {
        PathBuf::from("C:\\Program Files\\NestGate")
    }

    #[cfg(unix)]
    {
        if is_privileged() {
            PathBuf::from("/opt/nestgate")
        } else {
            dirs::home_dir()
                .unwrap_or_else(|| PathBuf::from("."))
                .join(".local/share/nestgate")
        }
    }
}

fn is_privileged() -> bool {
    #[cfg(unix)]
    {
        nix::unistd::geteuid().is_root()
    }

    #[cfg(windows)]
    {
        // Simple check - in production this should be more robust
        std::env::var("USERPROFILE")
            .map(|p| p.contains("Administrator"))
            .unwrap_or(false)
    }
}
